create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
create table TRXN_bank (bank_id integer not null, bank_name varchar(255), primary key (bank_id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
create table TRXN_bank (bank_id integer not null, bank_name varchar(255), primary key (bank_id))
create table TRXN_bank (bank_id integer not null, bank_name varchar(255), primary key (bank_id))
create table TRXN_bank (bank_id integer not null, bank_name varchar(255), primary key (bank_id))
create table TRXN_bank (bank_id integer not null, bank_name varchar(255), primary key (bank_id))
create table TRXN_original_SMS (TRXN_original_SMS_id integer not null, TRXN_id integer not null, original_SMS varchar(255), primary key (TRXN_original_SMS_id))
